* Introdução
  O trabalho consiste em projetar uma solução para o problema clássico de
  leitores e escritores, de modo a garantir a ausência de *inanição* das threads.
  Para isso, foi empregada uma estratégia de sincronização que visa tentar
  alcançar uma prioridade igualitária entre leitores e escritores.
  
* Compilando e executando
  Para compilar o programa concorrente, basta-se executar o seguinte comando: \\
  ~gcc leit_esc.c -lpthread -Wall~
  
  Para se executar o programa, deve-se efetuar a seguinte instrução no terminal: \\
  ~./a.out <nº de leitores> <nº de escritores> <nº de leituras> <nº de escritas> <arquivo de log>~
  
  E por fim, para se usar o script de validação do log, executa-se: \\
  ~python validador.py <nome do arquivo de log>~

* O programa
  Uma explicação mais detalhada da aplicação se encontra no relatório disponível
  neste repositório.
  
  Em linhas gerais, este programa consiste num modelo de solução para o problema
  anteriormente citado de leitores e escritores, que busca minizizar a possiblidade
  de inanição com a combinação de contadores de threads aguardando inativas e
  uma variável de controle para definir qual tipo de thread inativa será reativada,
  entre escritores e leitores.
